version: '3.8'

services:
  backend:
    build:
      context: ./aqua-vision-backend
      dockerfile: Dockerfile
    container_name: aqua-vision-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./aqua-vision-frontend
      dockerfile: Dockerfile
    container_name: aqua-vision-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
